### ISSUE TITLE
Failed to load Python extension for LZ4 support. LZ4 compression will not be available

### ISSUE THREAD

**Issue by John-Mccarty** [ori-drs/allan_variance_ros#11]
thanks for sharing your work.
when I try to run  rosrun allan_variance_ros cookbag.py --input workspace/imu_calibration.bag --output workspace/cooked_rosbag.bag
I get this error :Failed to load Python extension for LZ4 support. LZ4 compression will not be available.
I instaled lz4 and roslz4 package but it still occur.What is the mistake?

**Comment by boeun98** [comment]
I have a same problem. 
How can I solve that......?

**Comment by raabuchanan** [comment]
Have you installed `rosbag` ? Try `pip install rosbag`

Also, this step is not strictly required. You can use a non pre-processed rosbag.

**Comment by lmz-whu** [comment]
ROS1 depends on python2.7, then your env is python3. 
I solve this by reinstalling roslz4 to python3.
1. delete roslz4 in `/opt/ros/xxx/lib/python2.7/site-packages`
2. downlaod roslz4 from `https://rospypi.github.io/simple`
3. pip install
