### ISSUE TITLE
compile err

### ISSUE THREAD

**Issue by improve100** [ori-drs/allan_variance_ros#12]
1. uint64_t
catkin_build/src/allan_variance_ros/include/allan_variance_ros/ImuMeasurement.hpp:14:3: error: ‘uint64_t’ does not name a type uint64_t t{};       ///< ROS time message received (nanoseconds).

add #include <stdint.h> in ImuMeasurement.hpp file.

2.  error: expected unqualified-id before ‘using’
catkin_build/src/allan_variance_ros/include/allan_variance_ros/AllanVarianceComputor.hpp:17:1: error: expected unqualified-id before ‘using’
using EigenVector = std::vector<T, Eigen::aligned_allocator<T>>;

**Comment by Okayuh** [comment]
same problem here at Ubuntu16.04.
Which Ubuntu version is recommended?

**Comment by raabuchanan** [comment]
I use Ubuntu 20.04 LTS with ROS Noetic
I can't guarantee this will work out of the box for other versions.

**Comment by zoldaten** [comment]
Ubuntu 20.04 LTS with ROS Noetic compiled OK.
Raspbian buster with ROS Noetic failed.

**Comment by raabuchanan** [comment]
I don't have a raspberry pi to test with but in general I recommend Ubuntu 20.04 LTS with ROS Noetic
