### ISSUE TITLE
about analysis.py

### ISSUE THREAD

**Issue by boeun98** [ori-drs/allan_variance_ros#16]
I have a problem.

I ran the analysis.py 

but the biases about accelerometer and gyroscope x,y, and z have nan value.

What should I do???

results
.
.
![acceleration](https://user-images.githubusercontent.com/72862584/166153999-3edb3ae3-2de8-4239-a10b-2d9725c8e619.png)
.
.
![gyro](https://user-images.githubusercontent.com/72862584/166154005-b0a18005-02aa-4750-99e4-454897ec5f52.png)
.
.
.
.
.
.
And I modified the code in analysis.py

`logx = np.log(x) and logy = np.log(y)`  ----> add   `logx = np.nan_to_num(logx) and logy = np.nan_to_num(logy)`

`coeffs, _ = curve_fit(line_func, logx, logy, bounds=~~~~~~`  ----> `coeffs, _ = curve_fit(line_func, logx, logy)`

**Comment by raabuchanan** [comment]
Hi @boeun98
I think you don't have enough data, it looks like you recorded less than 100s.
Absolute minimum you 1 hour of data but ideally 3 hours or more for better accuracy.
