### ISSUE TITLE
I want to know what the two graphs mean?

### ISSUE THREAD

**Issue by boeun98** [ori-drs/allan_variance_ros#19]
Thanks for your project.

I want to know what the two graphs mean???

What do the star, circle, and triangle mean?
.
.
.
![acceleration](https://user-images.githubusercontent.com/72862584/169693869-960e0384-50c5-4a0e-aae9-7f593569db6c.png)
.
.
.
.
![gyro](https://user-images.githubusercontent.com/72862584/169693874-aff63682-d41c-4976-9cc1-5326cc598908.png)

**Comment by raabuchanan** [comment]
The circles indicate the 1s intercept of -0.5 slope which is used to compute `Velocity Random Walk` and `Angle Random Walk`
The triangles indicate the lowest value which is used to compute `Bias Instability`.
The stars indicate the 3s intercept of 0.5 slope which is used to compute `Accel Random Walk` and `Rate Random Walk`
