### ISSUE TITLE
Unable to use allan_variance

### ISSUE THREAD

**Issue by Hateley123** [ori-drs/allan_variance_ros#33]
I am following the instructions on how to use your system and I was able to output the information into a new bag using step 2. However, when I true to do step 3 I get the following error if I have roscore running

**Error**
ig-handle@ig-handle:~/catkin_ws/src/allan_variance_ros$ rosrun allan_variance_ros allan_variance /home/ig-handle/catkin_ws/src/ig_handle/scripts/cooked_rosbag.bag 

/home/ig-handle/catkin_ws/src/ig_handle/scripts/allan_imu_config.yaml 
[ INFO] [1674847354.590778010]: Bag Folder = /home/ig-handle/catkin_ws/src/ig_handle/scripts/cooked_rosbag.bag

[ INFO] [1674847354.591459928]: Config File = /home/ig-handle/catkin_ws/src/ig_handle/scripts/allan_imu_config.yaml

terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::directory_iterator::construct: Not a directory: "/home/ig-handle/catkin_ws/src/ig_handle/scripts/cooked_rosbag.bag"

Aborted (core dumped)

If i do not have roscore running then I get the following error

**Error**

[ERROR] [1674847344.161721965]: [registerPublisher] Failed to contact master at [localhost:11311].  Retrying...

Now in both instances I know the file exists because i see in the directory and when I press tab it selects the file in the terminal. Do you know how to fix this problem

**Comment by minhlenhat21** [comment]
I've met the same error, do u solve it yet
