### ISSUE TITLE
What is the meaning of measure_rate in the configuration file? Is it related to the IMU sampling rate?

### ISSUE THREAD

**Issue by mppcasc** [ori-drs/allan_variance_ros#9]
Thanks

**Comment by seajayshore** [comment]
+1 
Can someone please confirm the difference between measure_rate & imu_rate in the config files?

**Comment by gsanya** [comment]
+1

**Comment by feixh** [comment]
Did anyone figure out what measure_rate means?

**Comment by stephanietsuei** [comment]
Looking through the code, this is what I think is going on...

`measure_rate` can be set to a number smaller than `imu_rate` to subsample the IMU data. This means that the total computation will take less time, but that you are throwing away higher-frequency information. In my own little experiment, I set `measure_rate` to 1/4 `imu_rate`. There was very little change to the values of `accelerometer_random_walk` and `gyroscope_random_walk`, but the noise parameters were between 50 and 100% larger when the data was subsampled.

**Comment by raabuchanan** [comment]
Yes @stephanietsuei is correct. I've updated the comment in the config file to clarify this.
